#include "\incs\patches.hpp"
#include "\incs\anims.hpp"
#include "\incs\vehicles.hpp"
#include "\incs\ammo.hpp"
#include "\incs\magazines.hpp"
#include "\incs\weapons.hpp"
#include "\incs\glasses.hpp"
#include "\incs\gui.hpp"